#!/usr/bin/env bash
# generate_keys_and_populate_did.sh
# Generates Ed25519 key pairs for attestor and TSA, populates DID resolver
# Generated by Microsoft Copilot, April 3, 2026
# CC-BY-ND-4.0 — TriPod LLC
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
KEYS_DIR="$ROOT_DIR/services/keys"
DID_RESOLVER_FILE="$ROOT_DIR/services/did_resolver/did_docs.json"

mkdir -p "$KEYS_DIR"

echo "=== STOICHEION Key Generator ==="
echo "Generating Ed25519 keys for attestor and TSA..."

# Attestor key pair
if [ ! -f "$KEYS_DIR/attestor_ed25519.raw" ]; then
  python3 -c "
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives import serialization
key = Ed25519PrivateKey.generate()
priv = key.private_bytes(encoding=serialization.Encoding.Raw, format=serialization.PrivateFormat.Raw, encryption_algorithm=serialization.NoEncryption())
pub = key.public_key().public_bytes(encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw)
open('$KEYS_DIR/attestor_ed25519.raw','wb').write(priv)
open('$KEYS_DIR/attestor_pub.raw','wb').write(pub)
print('Attestor keys written')
"
else
  echo "Attestor keys already exist"
fi

# TSA key pair
if [ ! -f "$KEYS_DIR/tsa_ed25519.raw" ]; then
  python3 -c "
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives import serialization
key = Ed25519PrivateKey.generate()
priv = key.private_bytes(encoding=serialization.Encoding.Raw, format=serialization.PrivateFormat.Raw, encryption_algorithm=serialization.NoEncryption())
pub = key.public_key().public_bytes(encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw)
open('$KEYS_DIR/tsa_ed25519.raw','wb').write(priv)
open('$KEYS_DIR/tsa_pub.raw','wb').write(pub)
print('TSA keys written')
"
else
  echo "TSA keys already exist"
fi

# Build DID resolver document
ATT_PUB_B64=$(python3 -c "import base64; print(base64.b64encode(open('$KEYS_DIR/attestor_pub.raw','rb').read()).decode())")
TSA_PUB_B64=$(python3 -c "import base64; print(base64.b64encode(open('$KEYS_DIR/tsa_pub.raw','rb').read()).decode())")

mkdir -p "$(dirname "$DID_RESOLVER_FILE")"
cat > "$DID_RESOLVER_FILE" <<EOF
{
  "did:local:gardener": {
    "id": "did:local:gardener",
    "verificationMethod": [
      {
        "id": "did:local:gardener#key-1",
        "type": "Ed25519VerificationKey2018",
        "publicKeyBase64": "$ATT_PUB_B64"
      }
    ]
  },
  "did:local:tsa": {
    "id": "did:local:tsa",
    "verificationMethod": [
      {
        "id": "did:local:tsa#key-1",
        "type": "Ed25519VerificationKey2018",
        "publicKeyBase64": "$TSA_PUB_B64"
      }
    ]
  }
}
EOF

echo "DID resolver document written to $DID_RESOLVER_FILE"
echo "=== Done. Start the Docker Compose stack next. ==="
