#!/usr/bin/env python3
"""
run_local_testbed.py

Automated end-to-end test harness for STOICHEION local testbed.
Generated by Microsoft Copilot, April 3, 2026.
CC-BY-ND-4.0 — TriPod LLC

Automates:
  - Key generation
  - Docker Compose stack startup
  - Sample artifact creation
  - Term registration via attestation API
  - Attestation verification
  - Stack shutdown and cleanup
"""

import os
import subprocess
import time
import json
import hashlib
import requests
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def run(cmd, cwd=None):
    print(f"RUN: {' '.join(cmd)}")
    subprocess.check_call(cmd, cwd=cwd)


def ensure_keys():
    script = ROOT / "scripts" / "generate_keys_and_populate_did.sh"
    if not script.exists():
        print("WARNING: Key generation script not found. Skipping.")
        return
    run(["bash", str(script)])


def docker_up():
    run(["docker", "compose", "up", "--build", "-d"], cwd=str(ROOT))


def docker_down():
    run(["docker", "compose", "down", "--volumes", "--remove-orphans"], cwd=str(ROOT))


def wait_for_services(timeout=30):
    print("Waiting for services...")
    endpoints = [
        ("Attestation API", "http://localhost:8000/v1/register/term"),
        ("TSA", "http://localhost:8001/request"),
        ("Transparency Log", "http://localhost:8002/append"),
        ("DID Resolver", "http://localhost:8003/1.0/identifiers/did:local:gardener"),
    ]
    start = time.time()
    for name, url in endpoints:
        while time.time() - start < timeout:
            try:
                r = requests.get(url, timeout=2)
                if r.status_code < 500:
                    print(f"  {name}: OK")
                    break
            except Exception:
                time.sleep(1)
        else:
            print(f"  {name}: TIMEOUT")


def create_artifact():
    path = ROOT / "test_artifact.txt"
    nonce = f"STOICHEION-TEST-{int(time.time())}"
    path.write_text(f"Unique nonce: {nonce}\n")
    print(f"Created artifact: {path} (nonce: {nonce})")
    return path


def sha256_hex(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def register_artifact(artifact_path):
    h = sha256_hex(artifact_path)
    payload = {
        "subject_hash": h,
        "subject_type": "seed",
        "canonical_mapping": "T001",
    }
    print(f"Registering artifact (hash: {h[:16]}...)")
    r = requests.post(
        "http://localhost:8000/v1/register/term",
        json=payload,
        timeout=10,
    )
    if r.status_code != 201:
        print(f"ERROR: Registration failed ({r.status_code}): {r.text}")
        return None
    att = r.json()
    att_path = ROOT / "test_attestation.json"
    att_path.write_text(json.dumps(att, indent=2))
    print(f"Attestation saved: {att_path}")
    print(f"  ID: {att.get('id')}")
    print(f"  Transparency Index: {att.get('transparencyIndex')}")
    return att_path


def verify_attestation(att_path, artifact_path):
    verifier = ROOT / "verifier" / "stoicheion_verifier.py"
    if not verifier.exists():
        print("WARNING: Verifier not found. Skipping verification.")
        return
    run(["python3", str(verifier), str(att_path), str(artifact_path)])


def cleanup():
    for f in ["test_artifact.txt", "test_attestation.json"]:
        p = ROOT / f
        if p.exists():
            p.unlink()
            print(f"Cleaned up: {p}")


def main():
    print("=" * 60)
    print("STOICHEION Local Testbed — End-to-End Test")
    print("=" * 60)

    ensure_keys()
    docker_up()

    try:
        wait_for_services()
        artifact = create_artifact()
        att = register_artifact(artifact)
        if att:
            verify_attestation(att, artifact)
            print("\n=== TEST COMPLETE ===")
        else:
            print("\n=== TEST FAILED: Registration error ===")
    finally:
        print("\nShutting down stack...")
        docker_down()
        cleanup()


if __name__ == "__main__":
    main()
